spring.application.name=InternNova

cloudinary.cloud_name=dvq9saspo
cloudinary.api_key=786534154659239
cloudinary.api_secret=M1xR4vC28L5u3mvy5-ry3FSAw4E

spring.data.mongodb.uri=mongodb+srv://anshulpatel2023_db_user:Anshu755@internnova-development.mcksg7e.mongodb.net/internnova?appName=InternNova-Development
spring.data.mongodb.database=InternNova-Development